# Generated by Django 6.0.5 on 2026-05-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_solicitacaocadastro_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
            },
        ),
        migrations.AlterModelOptions(
            name='solicitacaocadastro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitação de Cadastro', 'verbose_name_plural': 'Solicitações de Cadastro'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Dev'), (2, 'Nivel 2 - Gestor'), (3, 'Nivel 3 - Engenheiro')], default=3, verbose_name='Nível de acesso'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_crea',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número do CREA'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='analisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_analisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='motivo_negacao',
            field=models.TextField(blank=True, verbose_name='Motivo da negação'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='numero_crea',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número do CREA'),
        ),
        migrations.CreateModel(
            name='Caderneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=150, verbose_name='Nome / Apelido da obra')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='cadernetas/icones/', verbose_name='Ícone da obra')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadernetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caderneta',
                'verbose_name_plural': 'Cadernetas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa contratante')),
                ('local_obra', models.CharField(max_length=200, verbose_name='Local da obra')),
                ('area_construir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área a construir')),
                ('area_ampliar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área a ampliar')),
                ('area_reformar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área a reformar')),
                ('area_regularizar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área a regularizar')),
                ('tipo_edificacao', models.CharField(choices=[('residencial_unifamiliar', 'Residencial Unifamiliar'), ('residencial_multifamiliar', 'Residencial Multifamiliar'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('publico', 'Público'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de edificação')),
                ('tipo_outros', models.CharField(blank=True, max_length=100, verbose_name='Tipo (outros)')),
                ('atividade_tecnica', models.CharField(choices=[('construcao', 'Construção'), ('ampliacao', 'Ampliação'), ('reforma', 'Reforma'), ('regularizacao', 'Regularização'), ('outros', 'Outros')], max_length=20, verbose_name='Atividade técnica')),
                ('atividade_outros', models.CharField(blank=True, max_length=100, verbose_name='Atividade (outros)')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor_obra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da obra')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='em_andamento', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caderneta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='app.caderneta', verbose_name='Caderneta')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='app.proprietario', verbose_name='Proprietário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável técnico')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RelatoDeVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da visita')),
                ('opcoes_servicos', models.JSONField(default=list, verbose_name='Serviços verificados')),
                ('conformidade', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme'), ('parcial', 'Parcialmente conforme')], max_length=15, verbose_name='Conformidade')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('decisoes_tecnicas', models.TextField(blank=True, verbose_name='Decisões técnicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='app.recibo', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Relato de Visita',
                'verbose_name_plural': 'Relatos de Visita',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('recibo', 'Recibo'), ('relato', 'Relato de Visita'), ('termo', 'Termo de Conclusão')], max_length=10, verbose_name='Tipo')),
                ('autentique_id', models.CharField(max_length=100, verbose_name='ID Autentique')),
                ('pdf_assinado', models.FileField(blank=True, null=True, upload_to='pdfs_assinados/', verbose_name='PDF assinado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcialmente assinado'), ('concluido', 'Concluído'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='app.recibo')),
                ('relato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='app.relatodevisita')),
            ],
            options={
                'verbose_name': 'Documento de Assinatura',
                'verbose_name_plural': 'Documentos de Assinatura',
            },
        ),
        migrations.CreateModel(
            name='Signatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('engenheiro', 'Engenheiro'), ('proprietario', 'Proprietário')], max_length=15, verbose_name='Tipo')),
                ('link_assinatura', models.URLField(blank=True, verbose_name='Link de assinatura')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejeitado em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('geolocation', models.CharField(blank=True, max_length=100, verbose_name='Geolocalização')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatarios', to='app.documentoassinatura')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
            },
        ),
        migrations.CreateModel(
            name='TermoDeConclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('decisoes_tecnicas', models.TextField(blank=True, verbose_name='Decisões técnicas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo', to='app.recibo', verbose_name='Recibo')),
            ],
            options={
                'verbose_name': 'Termo de Conclusão',
                'verbose_name_plural': 'Termos de Conclusão',
            },
        ),
        migrations.AddField(
            model_name='documentoassinatura',
            name='termo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='app.termodeconclusao'),
        ),
    ]
