# Generated by Django 6.0.5 on 2026-05-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proprietario_alter_solicitacaocadastro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='relatodevisita',
            name='recibo',
        ),
        migrations.RemoveField(
            model_name='termodeconclusao',
            name='recibo',
        ),
        migrations.AlterModelOptions(
            name='proprietario',
            options={'verbose_name': 'Proprietario', 'verbose_name_plural': 'Proprietarios'},
        ),
        migrations.AlterModelOptions(
            name='recibo',
            options={'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaocadastro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitacao de Cadastro', 'verbose_name_plural': 'Solicitacoes de Cadastro'},
        ),
        migrations.AlterField(
            model_name='caderneta',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='cadernetas/icones/', verbose_name='Icone da obra'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Dev'), (2, 'Nivel 2 - Gestor'), (3, 'Nivel 3 - Engenheiro')], default=3, verbose_name='Nivel de acesso'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_crea',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero do CREA'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='area_ampliar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area a ampliar'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='area_construir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area a construir'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='area_reformar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area a reformar'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='area_regularizar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Area a regularizar'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='atividade_tecnica',
            field=models.CharField(choices=[('construcao', 'Construcao'), ('ampliacao', 'Ampliacao'), ('reforma', 'Reforma'), ('regularizacao', 'Regularizacao'), ('outros', 'Outros')], max_length=20, verbose_name='Atividade tecnica'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='data',
            field=models.DateField(verbose_name='Data da obra'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='app.proprietario', verbose_name='Proprietario'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='tipo_edificacao',
            field=models.CharField(choices=[('residencial_unifamiliar', 'Residencial Unifamiliar'), ('residencial_multifamiliar', 'Residencial Multifamiliar'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('publico', 'Publico'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de edificacao'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel tecnico'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='motivo_negacao',
            field=models.TextField(blank=True, verbose_name='Motivo da negacao'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='numero_crea',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numero do CREA'),
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da visita')),
                ('opcoes_servicos', models.TextField(help_text='Marque os servicos realizados', verbose_name='Servicos executados')),
                ('conformidade', models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Nao conforme'), ('parcial', 'Parcialmente conforme')], max_length=20, verbose_name='Conformidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('decisoes_tecnicas', models.TextField(blank=True, verbose_name='Decisoes tecnicas')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='app.recibo')),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('decidido', models.BooleanField(default=False, verbose_name='Decidido')),
                ('decisoes_tecnicas', models.TextField(blank=True, verbose_name='Decisoes tecnicas')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pronto_assinar', 'Pronto para assinar'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo', to='app.recibo')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
            },
        ),
        migrations.DeleteModel(
            name='DocumentoAssinatura',
        ),
        migrations.DeleteModel(
            name='Signatario',
        ),
        migrations.DeleteModel(
            name='RelatoDeVisita',
        ),
        migrations.DeleteModel(
            name='TermoDeConclusao',
        ),
    ]
